const { onDocumentCreated, onDocumentUpdated } = require("firebase-functions/v2/firestore");
const { initializeApp } = require("firebase-admin/app");
const { getFirestore } = require("firebase-admin/firestore");
const { getMessaging } = require("firebase-admin/messaging");
initializeApp(); const db = getFirestore();
async function tokensFor(field,value){const s=await db.collection("deviceTokens").where(field,"==",value).get();return s.docs.map(d=>({id:d.id,token:d.data().token})).filter(x=>x.token);}
async function notifyDevices(devices,title,body,data={}){if(!devices.length)return;const response=await getMessaging().sendEachForMulticast({tokens:devices.map(x=>x.token),notification:{title,body},data:Object.fromEntries(Object.entries(data).map(([k,v])=>[k,String(v)])),android:{priority:"high",notification:{channelId:"roros_orders",sound:"default",defaultVibrateTimings:true}}});const invalid=new Set(["messaging/invalid-registration-token","messaging/registration-token-not-registered"]);await Promise.all(response.responses.map((x,i)=>!x.success&&invalid.has(x.error?.code)?db.collection("deviceTokens").doc(devices[i].id).delete():null).filter(Boolean));}
exports.notifyAdminNewOrder=onDocumentCreated("orders/{orderId}",async e=>{const o=e.data?.data();if(!o)return;await notifyDevices(await tokensFor("role","admin"),"🍽️ New Roro's Cravings Order",`${o.customerName||"A customer"} placed an order worth ₱${Number(o.total||0).toLocaleString("en-PH")}.`,{type:"new_order",orderId:e.params.orderId});});
exports.notifyCustomerStatus=onDocumentUpdated("orders/{orderId}",async e=>{const b=e.data?.before.data(),a=e.data?.after.data();if(!b||!a||b.status===a.status||!a.userId)return;await notifyDevices(await tokensFor("uid",a.userId),"Order Status Updated",`Your order ${e.params.orderId} is now ${a.status}.`,{type:"status_update",orderId:e.params.orderId,status:a.status});});
exports.notifyNewChat=onDocumentCreated("orders/{orderId}/messages/{messageId}",async e=>{const m=e.data?.data();if(!m)return;const o=(await db.collection("orders").doc(e.params.orderId).get()).data();if(!o)return;const admin=m.senderRole==="admin";await notifyDevices(admin?await tokensFor("uid",o.userId):await tokensFor("role","admin"),admin?"💬 Roro's Cravings replied":"💬 New Customer Message",m.text||"You have a new order message.",{type:"chat",orderId:e.params.orderId});});
